#Login Page Elements
txt_loginUserName="name:userName"
txt_loginPassWord="name:password"
btn_signIN="xpath://input[@name='submit']"
Flight_page="xpath://a[normalize-space()='Flights']"

#Registration Page Elements
link_Reg="link:REGISTER"
txt_firstName="name:firstName"
txt_lastName="name:lastName"
txt_phone="name:phone"
txt_email="name:userName"
txt_add1="name:address1"
txt_city="name:city"
txt_state="name:state"
txt_postalCode="name:postalCode"
drp_country="name:country"
txt_userName="name:email"
txt_password="name:password"
txt_confirmPassword="name:confirmPassword"
btn_submit="xpath://input[@name='submit']"
